# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20170708_0912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
