# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20170709_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 13, 22, 17, 668049, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
