# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20170709_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
